app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager


class User(UserMixin, db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), unique=True)
    username = db.Column(db.String(60), unique=True)
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError('access denied')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def to_json(self):
        return dict(id=self.id,
                    username=self.username,
                    email=self.email)

    def __repr__(self):
        return '<User: {}>'.format(self.username)


# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/__init__.py
import os
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


# init SQLAlchemy so we can use it later in our models
db = SQLAlchemy()
login_manager = LoginManager()


def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = "123"
    app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///db.sqlite"

    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # app.config['TEMPLATES_AUTO_RELOAD'] = os.environ.get(
    #     'TEMPLATES_AUTO_RELOAD')
    # app.config['SEND_FILE_MAX_AGE_DEFAULT'] = os.environ.get(
    #     'SEND_FILE_MAX_AGE_DEFAULT')

    login_manager.init_app(app)
    login_manager.login_message = "Access Denied!, Log in to proceed"
    login_manager.login_view = "auth.login"

    db.init_app(app)
    db.create_all()
    migrate = Migrate(app, db, compare_type=True)
    

    # blueprint for auth routes in our app
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    # blueprint for agora
    from .agora import agora as agora_blueprint
    app.register_blueprint(agora_blueprint)

    from .agora_rtm import agora_rtm as agora_rtm_blueprint
    app.register_blueprint(agora_rtm_blueprint)

    return app

app/agora/__init__.py
from flask import Blueprint
agora = Blueprint('agora', '__init__')

from . import views  # isort:skip

app/agora/views.py
import os
import time
from flask import render_template, jsonify, request
from flask_login import login_required, current_user

from . import agora
from ..models import User
from .agora_key.RtcTokenBuilder import RtcTokenBuilder, Role_Attendee
from pusher import Pusher


# Instantiate a Pusher Client
pusher_client = Pusher(app_id="1340915",
                       key="361d34bd8ddf12fbb43a",
                       secret="d9593d6cebccfec91331",
                       ssl=True,
                       cluster="ap2"
                       )

@agora.route('/')
@agora.route('/agora')
@login_required
def index():
    users = User.query.all()
    all_users = [user.to_json() for user in users]
    return render_template('agora/index.html', title='Video Chat', allUsers=all_users)


@agora.route('/agora/pusher/auth', methods=['POST'])
def pusher_auth():
    auth_user = current_user.to_json()
    payload = pusher_client.authenticate(
        channel=request.form['channel_name'],
        socket_id=request.form['socket_id'],
        custom_data={
            'user_id': auth_user['id'],
            'user_info': {
                'id': auth_user['id'],
                'name': auth_user['username']
            }
        })
    return jsonify(payload)


@agora.route('/agora/token',  methods=['POST'])
def generate_agora_token():
    auth_user = current_user.to_json()
    appID = "144576c2e25c4a629ce399e7eab920b7"
    appCertificate = "63deaf61e2ff4a13b7c8474ea82a8eac"
    channelName = request.json['channelName']
    userAccount = auth_user['username']
    expireTimeInSeconds = 3600
    currentTimestamp = int(time.time())
    privilegeExpiredTs = currentTimestamp + expireTimeInSeconds

    token = RtcTokenBuilder.buildTokenWithAccount(
        appID, appCertificate, channelName, userAccount, Role_Attendee, privilegeExpiredTs)

    return jsonify({'token': token, 'appID': appID})


@agora.route('/agora/call-user',  methods=['POST'])
def call_user():
    auth_user = current_user.to_json()
    pusher_client.trigger(
        'presence-online-channel',
        'make-agora-call',
        {
            'userToCall': request.json['user_to_call'],
            'channelName': request.json['channel_name'],
            'from': auth_user['id']
        }
    )
    return jsonify({'message': 'call has been placed'})

app/agora_rtm/__init__.py
from flask import Blueprint
agora_rtm = Blueprint('agora_rtm', '__init__')

from . import views  # isort:skip

app/agora_rtm/views.py
import os
import time
from flask import render_template, jsonify, request
from flask_login import login_required, current_user

from agora_token_builder import RtcTokenBuilder, RtmTokenBuilder

from . import agora_rtm
from ..models import User


ROLE_RTM_USER = 1
ROLE_PUBLISHER = 1


@agora_rtm.route('/agora-rtm')
@login_required
def index():
    users = User.query.all()
    all_users = [user.to_json() for user in users]
    return render_template('agora_rtm/index.html', title='Agora Video Call with RTM', allUsers=all_users, agoraAppID=os.environ.get('AGORA_APP_ID'))


@agora_rtm.route('/users')
def fetch_users():
    users = User.query.all()
    all_users = [user.to_json() for user in users]
    return jsonify(all_users)


@agora_rtm.route('/agora-rtm/token',  methods=['POST'])
def generate_agora_token():
    auth_user = current_user.to_json()
    appID = os.environ.get('AGORA_APP_ID')
    appCertificate = os.environ.get('AGORA_APP_CERTIFICATE')
    channelName = request.json['channelName']
    userAccount = auth_user['username']
    expireTimeInSeconds = 3600
    currentTimestamp = int(time.time())
    privilegeExpiredTs = currentTimestamp + expireTimeInSeconds

    token = RtcTokenBuilder.buildTokenWithAccount(
        appID, appCertificate, channelName, userAccount, ROLE_PUBLISHER, privilegeExpiredTs)

    rtm_token = RtmTokenBuilder.buildToken(
        appID, appCertificate, userAccount, ROLE_RTM_USER, privilegeExpiredTs)
    return jsonify({'token': token, 'rtm_token': rtm_token, 'appID': appID})

app/templates/agora/index.html
{% extends "base.html" %} {% block head_scripts %}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='agora/index.css') }}"
/>
<script src="https://cdn.agora.io/sdk/release/AgoraRTCSDK-3.3.1.js"></script>
{% endblock head_scripts %} {% block content%}
<div id="app">
  <div class="container my-5">
    <div class="row">
      <div class="col">
        <div class="btn-group" role="group" id="btnGroup">
          {% for singleUser in allUsers%} {% if singleUser['id'] !=
          current_user['id'] %}
          <button
            type="button"
            class="btn btn-primary mr-2 my-2"
            @click="placeCall('{{singleUser.id}}','{{singleUser['username']}}')"
          >
            Call {{ singleUser['username'] }}
            <span class="badge badge-light"
              >${ getUserOnlineStatus({{singleUser.id}})}</span
            >
          </button>

          {% endif %} {% endfor %}
        </div>
      </div>
    </div>

    <!-- Incoming Call  -->
    <div class="row my-5" v-if="incomingCall">
      <div class="col-12">
        <p>Incoming Call From <strong>${ incomingCaller }</strong></p>
        <div class="btn-group" role="group">
          <button
            type="button"
            class="btn btn-danger"
            data-dismiss="modal"
            @click="declineCall"
          >
            Decline
          </button>
          <button
            type="button"
            class="btn btn-success ml-5"
            @click="acceptCall"
          >
            Accept
          </button>
        </div>
      </div>
    </div>
    <!-- End of Incoming Call  -->
  </div>

  <section id="video-container" v-if="callPlaced">
    <div id="local-video"></div>
    <div id="remote-video"></div>

    <div class="action-btns">
      <button type="button" class="btn btn-info" @click="handleAudioToggle">
        ${ mutedAudio ? "Unmute" : "Mute" }
      </button>
      <button
        type="button"
        class="btn btn-primary mx-4"
        @click="handleVideoToggle"
      >
        ${ mutedVideo ? "ShowVideo" : "HideVideo" }
      </button>
      <button type="button" class="btn btn-danger" @click="endCall">
        EndCall
      </button>
    </div>
  </section>
</div>
{% endblock content %}

<!-- Add Scripts -->
{% block bottom_scripts%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/pusher/7.0.3/pusher.min.js"></script>
<script>
  // Replace 420e941c25574fda6378 with your own Pusher Key
  window.pusher = new Pusher("420e941c25574fda6378", {
    authEndpoint: "{{ url_for('agora.pusher_auth') }}",
    auth: {
      headers: {
        "X-CSRFToken": "{{ csrf_token }}",
      },
    },
  });

  const AUTH_USER = "{{current_user['username']}}";
  const AUTH_USER_ID = "{{current_user['id']}}";
  const CSRF_TOKEN = "{{ csrf_token }}";
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="{{ url_for('static', filename='agora/index.js') }}"></script>
{% endblock bottom_scripts %}

app/templates/agora_rtm/index.html
{% extends "base.html" %} {% block head_scripts %}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='agora/index.css') }}"
/>
<script src="https://download.agora.io/sdk/release/AgoraRTC_N-4.7.0.js"></script>
<script src="{{ url_for('static', filename='agora_rtm/agora-rtm.js') }}"></script>
{% endblock head_scripts %} {% block content%}
<div id="app">
  <div class="container my-5">
    <div class="row">
      <div class="col" v-if="isLoggedIn">
        <div class="btn-group" role="group" id="btnGroup">
          {% for singleUser in allUsers%} {% if singleUser['id'] !=
          current_user['id'] %} {% set username = singleUser['username']%}
          <button
            type="button"
            class="btn btn-primary mr-2 my-2"
            @click="placeCall('{{username}}')"
          >
            Call {{ username}}
            <span class="badge badge-light"
              >${updatedOnlineStatus?.["{{username}}"]?.toLowerCase() ||
              'offline'}</span
            >
          </button>
          {% endif %} {% endfor %}
        </div>
      </div>
    </div>

    <div class="row my-5" v-if="isCallingUser">
      <div class="col-12">
        <p>${callingUserNotification}</p>
        <button type="button" class="btn btn-danger" @click="cancelCall">
          Cancel Call
        </button>
      </div>
    </div>

    <!-- Incoming Call  -->
    <div class="row my-5" v-if="incomingCall">
      <div class="col-12">
        <!-- <p>Incoming Call From <strong>${ incomingCaller }</strong></p> -->
        <p>${incomingCallNotification}</p>
        <div class="btn-group" role="group">
          <button
            type="button"
            class="btn btn-danger"
            data-dismiss="modal"
            @click="declineCall"
          >
            Decline
          </button>
          <button
            type="button"
            class="btn btn-success ml-5"
            @click="acceptCall"
          >
            Accept
          </button>
        </div>
      </div>
    </div>
    <!-- End of Incoming Call  -->
  </div>

  <section id="video-container" v-if="callPlaced">
    <div id="local-video" ref="localVideo"></div>
    <div id="remote-video" ref="remoteVideo"></div>

    <div class="action-btns">
      <button type="button" class="btn btn-info" @click="handleAudioToggle">
        ${ mutedAudio ? "Unmute" : "Mute" }
      </button>
      <button
        type="button"
        class="btn btn-primary mx-4"
        @click="handleVideoToggle"
      >
        ${ mutedVideo ? "ShowVideo" : "HideVideo" }
      </button>
      <button type="button" class="btn btn-danger" @click="endCall">
        EndCall
      </button>
    </div>
  </section>
</div>
{% endblock content %}

<!-- Add Scripts -->
{% block bottom_scripts%}
<script>
  const AUTH_USER = "{{current_user['username']}}";
  const AUTH_USER_ID = "{{current_user['id']}}";
  const CSRF_TOKEN = "{{ csrf_token }}";
  const AGORA_APP_ID = "{{agoraAppID}}";
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="{{ url_for('static', filename='agora_rtm/index.js') }}"></script>
{% endblock bottom_scripts %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Build A Scalable Video Chat Application With Agora"
    />
    <meta
      name="keywords"
      content="Video Call, Agora, Flask, Real Time Engagement"
    />
    <meta name="author" content="Kofi Obrasi Ocran" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    />
    <link
      href="{{ url_for('static', filename='auth/index.css') }}"
      rel="stylesheet"
    />

    {% block head_scripts%} {% endblock %}

    <title>{{title}} - Agora Flask</title>
  </head>
  <body>
    <main>
      <div class="container">
        {% if current_user.is_authenticated %}
        <div class="row">
          <div class="col-12 text-right">
            <a
              href="{{ url_for('auth.logout') }}"
              class="btn btn-outline-danger"
              >Log out {{current_user['username']}}</a
            >
          </div>
        </div>

        {% endif %}

        <div class="row">
          <div class="col-12 text-center">
            <img
              src="{{ url_for('static', filename='agora/agora-logo.png') }}"
              alt="Agora Logo"
              class="block img-fuild"
            />
          </div>
        </div>
        <section class="row">
          <div class="col-12 text-center">
            {% with messages = get_flashed_messages() %} {% if messages %}
            <div class="flashes">
              {% for message in messages %}
              <div class="alert alert-danger" role="alert">
                {{ message }}
                <button
                  type="button"
                  class="close"
                  data-dismiss="alert"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {% endfor %}
            </div>
            {% endif %} {% endwith %}
          </div>
        </section>
      </div>
      {% block content%} {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
    {% block bottom_scripts%} {% endblock %}
  </body>
</html>